# On-disk cache for raw Flex statements.
#
# A Flex report is regenerated by IBKR on every request and takes a few seconds
# to produce, so a dry run followed by a real run should not ask twice. Each
# statement is written verbatim and keyed by query and day: two runs on the
# same day share one fetch, and a run tomorrow fetches again.
#
# It lives under storage/ rather than tmp/ for the same reason the Monobank
# cache does: storage/ is a named Docker volume that survives
# `docker compose up -d`, while tmp/ is not mounted at all.
class IbkrImport::Cache
  ROOT = Rails.root.join("storage/ibkr")

  attr_reader :root

  # @param refresh [Boolean] ignore anything already cached and re-fetch
  # @param offline [Boolean] never call the API; a cache miss is an error.
  #   This is what lets the importer be exercised end to end against a fixture.
  def initialize(root: ROOT, refresh: false, offline: false)
    @root = Pathname.new(root)
    @refresh = refresh
    @offline = offline
  end

  def refresh? = @refresh
  def offline? = @offline

  # Returns the cached XML for `key`, calling the block on a miss.
  def fetch(key)
    file = path_for(key)

    if file.exist? && !refresh?
      return file.read
    end

    if offline?
      raise IbkrImport::Error,
            "offline mode: nothing cached at #{file}. Run once without OFFLINE=1, " \
            "or seed the file from a fixture with `rails ibkr:seed`."
    end

    payload = yield
    write(file, payload)
    payload
  end

  def path_for(key)
    root.join("#{key}.xml")
  end

  def cached?(key)
    path_for(key).exist?
  end

  private
    def write(file, payload)
      file.dirname.mkpath
      file.write(payload)
      file
    end
end
